In [64]:
import pandas as pd
data = pd.read_csv("train.csv")

In [31]:
import re

In [65]:
data = data[['context', 'target', 'output']]

In [66]:
data['output'] = data['output'].apply(lambda x: 0 if x == 'entailment' else 1)

In [67]:
data

,context,target,output
0,경찰은 현재 과학수사 수준이 사건 발생 당시보다 비약적으로 발전한 점에 착안해 지난...,국립과학수사연구원은 경찰의 의뢰를 받아들여 피해자 유류품을 분석했을 것이다.,0
1,다만 미국의 행동에 따라 조치를 취하겠다는 논리를 편 것은 여전히 트럼프 대통령의 ...,현시점에서는 아직 다음 미국 대선의 결과가 나오지 않았다.,0
2,우리나라 상반기 총 수출규모는 억 달러로 전년 동기대비 . 감소했는데 부산의 수출 ...,부산의 수출 감소 폭이 전국의 두 배에 달함에도 불구하고 그보다 수출규모가 작은 지...,0
3,이 흐름이 팬데믹 이후 심화했고 유럽에서 사회 안전망이 가장 잘 돼있다고 여겨지는 ...,코로나 이후로 빈곤 위기를 크게 느끼지 못했던 국가에서도 기아와 빈곤 문제가 심각해...,0
4,화이자는 독일 바이오엔테크와 백신을 공동개발했으며 미 식품의약국() 긴급승인을 거쳐...,화이자는 독일 바이오엔테크와 같이 백신을 개발했는데 최종 승인에는 이르지 못했다.,1
...,...,...,...
12014,한국농어촌공사는 년 말 한국국제협력단()로부터 약 억원에 수주를 받아 타당성 조사와...,는 한국농어촌공사의 개방형 방조제 구상을 약 억 원의 수주를 통해 지원하고 있다.,0
12015,국회 산자위는 일 전체회의를 열고 지난해 월 일 법안소위를 통과한 국가균형발전특별법...,대전과 충청남도가 혁신도시로 지정될 수 있는 국가균형발전특별법 개정안은 아직 본회의...,0
12016,보현 까르미는 프리미엄 건축마감재 브랜드로 이번 박람회에서 친환경 패널을 선보인다....,보현 친환경 패널은 불에 잘 타지 않는 소재이다.,0
12017,일 방역당국에 따르면 박정규 한화 이글스 사장은 이날 일부 선수의 자가격리를 해제해...,한화 이글스 군 선수들이 훈련할 수 있는 장소는 한 군데 뿐이 아니다.,0
12018,문제는 이뿐만이 아니다. 신종코로나 사태가 악화 일로를 걷고 있는 가운데 일부 지역...,신종코로나 사태가 악화 일로를 걸으면서 야생동물 암거래 시장들이 새롭게 생겨나는 것...,1

In [43]:
def extract_korean_with_punctuation(text):
    return re.findall(r'[가-힣\s.?!\-\[\]()"\']+', text)

# 각 셀에서 한글 및 문장부호만 추출하여 새로운 컬럼으로 나누기
data['context'] = data['input'].apply(lambda x: ''.join(extract_korean_with_punctuation(eval(x)['premise'])))
data['target'] = data['input'].apply(lambda x: ''.join(extract_korean_with_punctuation(eval(x)['proposition'])))

In [70]:
data2 = pd.read_csv("test.csv")

In [72]:
data = pd.concat([data, data2], axis = 0)

In [74]:
del data['Unnamed: 0']

In [76]:
len(data)

13521

In [75]:
data.to_csv("train.csv")

In [36]:
import json
import csv

def jsonl_to_csv(jsonl_file_path, csv_file_path):
    # jsonl 파일을 열고 각 줄을 읽어서 json 객체로 변환
    with open(jsonl_file_path, 'r', encoding='utf-8') as jsonl_file:
        json_list = [json.loads(line) for line in jsonl_file]
    
    # csv 파일에 쓰기
    with open(csv_file_path, 'w', newline='', encoding='utf-8') as csv_file:
        if not json_list:
            return  # json_list가 비어있다면 종료

        # csv 파일의 필드명 설정 (첫 번째 json 객체의 키를 사용)
        fieldnames = json_list[0].keys()
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)

        # 헤더 작성
        writer.writeheader()

        # json 객체들을 csv에 작성
        for json_obj in json_list:
            writer.writerow(json_obj)

# 사용 예시
jsonl_file_path = 'nikluge-te-2023-dev.jsonl'
csv_file_path = 'temp_test.csv'
jsonl_to_csv(jsonl_file_path, csv_file_path)

In [17]:
data

,id,input,output,context,target
0,nikluge-2023-te-test-000001,{'premise': '환경부와 국립공원공단은 지난 8일부터 지리산국립공원 천은사 ...,NaN,환경부와 국립공원공단은 지난 일부터 지리산국립공원 천은사 일대 상생의 길 탐방로 단...,이번 년도 월에 지리산을 오르는 등산객들은 무료로 천은사를 둘러볼 수 있다.
1,nikluge-2023-te-test-000002,{'premise': '이와 함께 행정적 부담을 없애기 위해 임시회 기간을 코로나1...,NaN,이와 함께 행정적 부담을 없애기 위해 임시회 기간을 코로나 해결을 위한 최소한의 기...,가짜뉴스가 확산되면 부산 시민들은 불안에 떨 것이다.
2,nikluge-2023-te-test-000003,"{'premise': '21일 한국콘텐츠진흥원과 업계에 따르면, 롯데월드의 첫 수혜...",NaN,일 한국콘텐츠진흥원과 업계에 따르면 롯데월드의 첫 수혜 대상은 좀비덤과 두다다쿵이 ...,월 일 즈음에 롯데월드 어드벤처를 방문하면 좀비 캐릭터를 볼 수 있을 것이다.
3,nikluge-2023-te-test-000004,{'premise': '신종 코로나바이러스 감염증(코로나19) 백신 개발 관련 소식...,NaN,신종 코로나바이러스 감염증(코로나) 백신 개발 관련 소식에 장중 수익률은 소폭 올랐...,미국 시간으로 일에도 미국 벤치마크 년 만기 국채 수익률은 전 거래일과 같았다.
4,nikluge-2023-te-test-000005,"{'premise': '하나금융투자, “내년 코스피 최고 2,900P, 성장률 2....",NaN,하나금융투자 내년 코스피 최고 성장률 . 전망 하나금융투자는 일 내년 코스피 전망...,하나금융투자는 한국 경제 성장률에 .를 기여했다.
...,...,...,...,...,...
1498,nikluge-2023-te-test-001499,{'premise': '시험성적서를 위조할 경우 적합성평가 취소 및 기자재 수거 등...,NaN,시험성적서를 위조할 경우 적합성평가 취소 및 기자재 수거 등의 처분을 받게 되며 취...,적합성평가 취소 처분을 받게 되면 이 날로부터 개월간 적합성 평가 대상이 될 수 없다.
1499,nikluge-2023-te-test-001500,{'premise': '이미 그의 생일을 축하하는 여러 형태의 광고와 이벤트 등 아...,NaN,이미 그의 생일을 축하하는 여러 형태의 광고와 이벤트 등 아이돌 세계 최초 한국 최...,지민의 생일을 축하하는 전 세계적인 역대급 광고는 아이돌 세계 최초다.
1500,nikluge-2023-te-test-001501,"{'premise': '제작진은 “서로를 다정하게 챙겨주며 진한 포옹을 나누다가도,...",NaN,제작진은 서로를 다정하게 챙겨주며 진한 포옹을 나누다가도 순식간에 분위기를 얼어붙게...,우다사은 일 오후 시 첫방송된다.
1501,nikluge-2023-te-test-001502,"{'premise': '먼저 구는 각종 요금 체납현황, 단전·단수내역 등 17개 기...",NaN,먼저 구는 각종 요금 체납현황 단전단수내역 등 개 기관의 빅데이터에 기반한 위기가구...,위기가구 발굴관리시스템만으로는 위험가구를 전부 파악할 수 없다.
1502,nikluge-2023-te-test-001503,{'premise': '현대자동차에 따르면 아이오닉5는 배터리용량에 따라 58kWh...,NaN,현대자동차에 따르면 아이오닉는 배터리용량에 따라 (킬로와트시)급은 천만원 급은 천만...,현대자동차의 아이오닉는 배터리용량이 많아져도 가격이 높아지진 않을 것이다.